name: Linter

on:
  push:
  pull_request:
    branches:
      - main

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        # requites to grab the history of the PR
        fetch-depth: 0

    - name: Set up Python
      # python version defined by .python-version file
      uses: actions/setup-python@v4

    - name: Install requirements
      run:  pip install pre-commit

    - name: Check code
      run:  pre-commit run --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }} --show-diff-on-failure
